# R Packages
install.packages("tidyverse")
install.packages("devtools")
devtools::install_github("rstudio/sparklyr")
devtools::install_github("tidyverse/dplyr")
devtools::install_github("tidyverse/ggplot2")
devtools::install_github("tidyverse/purrr")
install.packages("shiny")
devtools::install_github("rstudio/shiny")
install.packages("rmarkdown")
devtools::install_github("rstudio/rmarkdown")
install.packages("flexdashboard")
devtools::install_github("rstudio/flexdashboard")
install.packages("tensorflow")
devtools::install_github("rstudio/tensorflow")
install.packages("tidymodels")
install.packages("plumber")
devtools::install_github("trestletech/plumber")
